include $(CLEAR_VARS)

ifeq ($(TARGET_SEC_FP_REQUEST_FORCE_CALIBRATE),true)
    LOCAL_CFLAGS += -DREQUEST_FORCE_CALIBRATE
endif

ifneq ($(TARGET_SEC_FP_REQUEST_ENROLL_TYPE),)
    LOCAL_CFLAGS += -DREQUEST_ENROLL_TYPE=$(TARGET_SEC_FP_REQUEST_ENROLL_TYPE)
endif

include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)

include $(BUILD_PREBUILT)
